SET MAST_HOME=<%MAST_HOME%>
SET PATH=%MAST_HOME%;%PATH%
SET PATH=%MAST_HOME%\bin;%PATH%
SET PATH=%MAST_HOME%\usrbin;%PATH%
SET PATH=%MAST_HOME%\anaconda;%PATH%
SET PATH=%MAST_HOME%\anaconda\Scripts;%PATH%
