SET PYTHON_VERSION=3.11.6
SET MAST_HOME=%~dp0
SET PATH=%MAST_HOME%;%PATH%
SET PATH=%MAST_HOME%\bin;%PATH%
SET PATH=%MAST_HOME%\usrbin;%PATH%
SET PATH=%MAST_HOME%\python\%PYTHON_VERSION%;%PATH%
SET PATH=%MAST_HOME%\python\%PYTHON_VERSION%\Scripts;%PATH%
SET PATH=%MAST_HOME%\python\%PYTHON_VERSION%\Library\bin;%PATH%
